version: '3'
services:
  ##########################
  # Producer/Worker config #
  ##########################
  worker:
    build: ./worker/
    environment:
    - ZMQ_WORKER_ADDRESS=tcp://producer:3000
  producer:
    build: ./producer/
    environment:
    - ZMQ_PRODUCER_ADDRESS=tcp://*:3000
    - ZMQ_PRODUCER_INTERVAL=2000
  ##################
  # Pub/Sub config #
  ##################
  #subscriber:
  #  build: ./subscriber/
  #  environment:
  #  - ZMQ_SUB_ADDRESS=tcp://publisher:3100
  #  - ZMQ_SUB_TOPIC='kitty cats'
  #publisher:
  #  build: ./publisher/
  #  environment:
  #  - ZMQ_PUB_ADDRESS=tcp://*:3100
  #  - ZMQ_PUB_INTERVAL=2000
  # #########################
  # # Load balancing broker #
  # #########################
  cluster:
    build: ./cluster/
    environment:
    - ZMQ_CLUSTER_BACK_ADDRESS=tcp://127.0.0.1:12345
    - ZMQ_CLUSTER_FRONT_ADDRESS=tcp://127.0.0.1:123456
    - ZMQ_CLUSTER_CLIENTS=10
    - ZMQ_CLUSTER_WORKERS=3
